name: Homolog Tests

on:
  push:
    branches:
      - homo

jobs:
  test-cluster:
    runs-on: self-hosted
    environment: cluster

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version-file: "3.12"

      - name: Install Dependencies
        run: uv sync --frozen

      - name: Run Pre-Commit
        run: uv run pre-commit run --all-files

      - name: Run Tests (cluster datasets)
        run: uv run pytest -v
        env:
          DATASET_DIR: ${{ vars.DATASET_DIR }}
          ENV_VAR_X:   ${{ secrets.ENV_VAR_X }}
